# Generated by Django 5.2.1 on 2025-05-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(choices=[('Itau', 'Itau'), ('Nubank', 'Nubank'), ('Bradesco', 'Bradesco'), ('Caixa', 'caixa'), ('Santander', 'santander'), ('Inter', 'inter')], max_length=50)),
                ('status', models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'banco')},
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'entrada'), ('SAIDA', 'saida')], default='ENTRADA', max_length=10)),
                ('categoria', models.CharField(choices=[('Salario', 'salario'), ('Comida', 'comida'), ('Lazer', 'lazer'), ('Aluguel', 'aluguel'), ('Outros', 'outros')], default='Outros', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historicos', to='core.conta')),
            ],
        ),
    ]
